version: '3.8'
services:
  postgres:
    image: postgres:16.1
    container_name: marocan-postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=marocan_db
      - POSTGRES_USER=${DB_Username}
      - POSTGRES_PASSWORD=${DB_Password}
      - POSTGRES_HOST_AUTH_METHOD=trust
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: marocan-backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/marocan_db
      - SPRING_DATASOURCE_USERNAME=${DB_Username}
      - SPRING_DATASOURCE_PASSWORD=${DB_Password}

volumes:
  postgres-data: